<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Gvanda_Base::/backend/head/base.phtml)
    <title><?= __('标签文档信息') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">
    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class='container-fluid'>
        <!-- start page message -->
        <div class='row'>
            <template>Weline_Component::message.phtml</template>
        </div>
        <!-- end message -->
        <div class='row'>
            <div class='col-12'>
                <div class='card'>
                    <div class='card-body'>
                        <h4 class='card-title'>
                            <lang>标签文档</lang>
                        </h4>
                        <p class='card-title-desc'>
                            {{document.description}}
                        </p>
                        <p>
                            <lang>json数据</lang>
                        </p>
                        <hr>
                        <pre>{{document.json}}</pre>
                    </div>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div> <!-- container-fluid -->
    <!-- end main content-->
</div>
<!-- END layout-wrapper -->
@template(Weline_Admin::common/footer.phtml)
</body>
</html>
