<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <!--基础-->
    @template(Gvanda_Base::/backend/head/base.phtml)
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <!-- Responsive Table css -->
    <link href='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.css)' rel='stylesheet'
          type='text/css'/>
    <!-- Sweet Alert-->
    <link href="@static(Weline_Admin::assets/libs/sweetalert2/sweetalert2.min.css)" rel="stylesheet" type="text/css"/>
    <title><?= __('标签管理') ?></title>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topbar'/>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topnav'/>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class='page-content'>
            <div class='container-fluid'>
                <!-- start page title -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
                            <h4 class='mb-sm-0'>
                                <lang>开发>标签管理</lang>
                            </h4>

                            <div class='page-title-right'>
                                <ol class='breadcrumb m-0'>
                                    <li class='breadcrumb-item'><a href='javascript: void(0);'>
                                            <lang>开发</lang>
                                        </a></li>
                                    <li class='breadcrumb-item'><a href="@backend-url('*/backend/taglib/listing')">
                                            <lang>标签管理</lang>
                                        </a>
                                    </li>
                                    <li class='breadcrumb-item'>
                                        <a href="@backend-url('*/backend/taglib/listing')">
                                            <lang>列表</lang>
                                        </a>
                                    </li>
                                </ol>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <!-- start page message -->
                <div class='row'>
                    <template>Weline_Component::message.phtml</template>
                </div> <!-- end message -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='card'>
                            <div class='card-body'>
                                <h4 class='card-title'>
                                    <lang>开发-标签管理</lang>
                                </h4>
                                <p class='card-title-desc'>
                                    <lang>管理标签</lang>
                                </p>
                                <div class='table-rep-plugin'>
                                    <!-- search form -->
                                    <div class='row'>
                                        <div class='col-12'>
                                            <block class='Weline\Component\Block\Form\Search' id='taglib-search'
                                                   action='*/backend/taglib/listing' method='get' keyword='q' value=''
                                                   placeholder='请输入标签关键词回车搜索'></block>
                                        </div>
                                    </div>
                                    <!-- end search form -->
                                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                                        <table id='tech-companies-1' class='table table-striped table-bordered'>
                                            <thead>
                                            <tr>
                                                <th data-priority='1'>
                                                    <lang>标签ID</lang>
                                                </th>
                                                <th data-priority='2'>
                                                    <lang>标签</lang>
                                                </th>
                                                <th data-priority='2'>
                                                    <lang>系统</lang>
                                                </th>
                                                <th data-priority='3'>
                                                    <lang>模块</lang>
                                                </th>
                                                <th><?= __('创建时间') ?></th>
                                                <th><?= __('更新时间') ?></th>
                                                <th><?= __('操作') ?></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <foreach name="items" item="item" key="key">
                                                <tr style="vertical-align: middle;">
                                                    <td class='co-name'>{{item.taglib_id}}</td>
                                                    <td class='co-name'>{{item.name}}</td>
                                                    <td><has name="item.is_system == '1'"><span class="active text-success">是</span><else/><span class="disabled text-black-50">否</span></has></td>
                                                    <td>{{item.module_name}}</td>
                                                    <td class='co-name'>{{item.create_time}}</td>
                                                    <td class='co-name'>{{item.update_time}}</td>
                                                    <td class='co-name'>
                                                        <div class="d-flex gap-2">
                                                            <block class='Weline\Component\Block\OffCanvas'
                                                                   template='Weline_Component::off-canvas.phtml'
                                                                   cache='0'
                                                                   id='off_canvas_taglib_document'
                                                                   action="*/backend/taglib/document"
                                                                   target-tag="a"
                                                                   vars="item"
                                                                   action-params="{id: item.taglib_id}"
                                                                   target-button-class='text-info'
                                                                   title='查看文档'
                                                                   close-button-show='1'
                                                                   close-button-text='关闭'
                                                                   target-button-text='查看文档'
                                                                   direction='right'
                                                                   class-names='w-75'
                                                                   off-canvas-body-style=''
                                                            />
                                                        </div>
                                                    </td>
                                                </tr>
                                            </foreach>
                                            </tbody>
                                        </table>
                                        {{pagination}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

@template(Weline_Admin::common/footer.phtml)
</body>
</html>
